#!/bin/zsh

# Aliases file
# 
# Suffix aliases will only be found in .zshrc for compatibility purposes with
# bash and other POSIX(ish) shells

# Curl aliases for easy information
alias \
  weather="curl -s https://wttr.in; echo" \
  myip="curl -s https://ipecho.net/plain; echo" \
  crypto="curl -s https://cad.rate.sx; echo"
#
#replace ls with exa
alias \
  ls="exa -l -a --color=always --git --group-directories-first" \
  ll="exa -l --colour=always --git -u | egrep '^\.'"
#grep w/ color
alias \
  grep="rg --color=auto" \
  fgrep="fgrep --color=auto" \
  egrep="egrep --color=auto"

# flags
alias \
  cp="cp -i" \
  pipi="pip install --user"

# Shorten
alias \
  yt="youtube-dl" \
  dots="dotbare" \
  scim="sc-im" \
  vim="nvim" \
  charge="upower -i /org/freedesktop/UPower/devices/battery_CMB0" \
  brightness="brightnessctl" \
  tlmgr="tllocalmgr" \
  g="git" \
  em="emacslient -nw|emacs -nw"

# Directory control
alias \
  ..="cd .." \
  ...="cd ../.." \
  .4="cd ../../.." \
  .5="cd ../../../.."

# Portage
alias \
  emerge="doas emerge --ask" \
  secmerge="command emerge --search" \
  unmerge="emerge --ask --depclean" \
  eselect="doas eselect"

#Power control
alias reboot="doas reboot" \
  poweroff="doas poweroff" \
  shutdown="doas shutdown"

# youtube-dl
alias yt='youtube-dl --extract-audio --add-metadata --xattrs --embed-thumbnail --audio-quality 0 --audio-format mp3' \
  ytv='youtube-dl --merge-output-format mp4 -f "bestvideo+bestaudio[ext=m4a]/best" --embed-thumbnail --add-metadata'
