#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -m 1 &

bspc monitor -d dev www www sys doc games chat mus vid gfx

# Vanity
bspc config normal_border_color "#3e4451"
bspc config active_border_color "#c8ccd4"
bspc config border_width                2
bspc config window_gap                 24

# Layout
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Window rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a Discord desktop='^6'
bspc rule -a mpv state=floating
bspc rule -a slop manage=off


# Misc
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

# Fix cursor being incorrect
xsetroot -cursor_name left_ptr
hsetroot -fill ~/Pictures/wallpapers/onedark.png

# Window swallowing
. ~/.local/bin/bspwm_swallow
